---
# This playbook transfers required files to KVM hosts and creates VMs
- name: Create CVP VMs on KVM hosts
  hosts: all
  vars:
    ansible_connection: network_cli
    ansible_network_os: arista.eos.eos
    # ansible_connection: network_cli
    # ansible_network_os: eos
    ansible_user: admin
    ansible_password: admin
    # # ansible_become: yes
    # # ansible_become_method: enable
    # ansible_httpapi_use_ssl: true
    # ansible_httpapi_validate_certs: false
    # # ansible_httpapi_port: 443
    # ansible_python_interpreter: $(which python3) 
  tasks:
    - name: copy files
      net_put:
        src: "{{ item }}"
        dest: /mnt/flash/test-file-to-copy.txt
      with_items:
        - /workspaces/ceos-certs/test-file-to-copy.txt
